apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dock8sample
  name: dock8sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dock8sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dock8sample
    spec:
      containers:
      - image: soniramji/dock8sample
        name: dock8sample
        resources: {}
status: {}
imagePullSecrets:
  name: $KUBERNETES_SECRET_NAME
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dock8sample
  name: dock8sample
spec:
  ports:
  - name: 9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: dock8sample
  type: ClusterIP
status:
  loadBalancer: {}

